# -*- coding: utf-8 -*-
"""AYUSHtweetsentanalysisFINAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uSBP4eyI3cya5FsnIqXOiVqQpHzxbNiC
"""

#Description : Sentiment Analysis Application that parses tweets scraped from twitter using Python

#Importing libraries
import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

#Loading data
from google.colab import files
uploaded = files.upload()

#Getting data
log = pd.read_csv('Login.csv')

#Twitter API credentials
consumerKey = 'sKK4RcfLdVvfz1sOU6jgez4ch'
consumerSecret = '23YjSUz1yerd27DfIs63uP2xawAf1loPNdNwg2FvTucd3F4aeh'
accessToken = '1280815370308386818-tuGw07SclxLMixBDu4Iubwmk9cusMK'
accessTokenSecret = 'EKRYi2DbjPhocXlqSdrNkl75qxgEmJex9E6kxAlpXX7Sg'

#Creating an authentication object
authenticate = tweepy.OAuthHandler(consumerKey, consumerSecret)

#Setting access token and access token secret
authenticate.set_access_token(accessToken, accessTokenSecret)

#Creating API object while passing in the auth information
api = tweepy.API(authenticate, wait_on_rate_limit = True)

#Extracting data from twitter user
posts = api.user_timeline(screen_name ="JoeBiden", count= 100, lang = "en", tweet_mode="extended")

#Printing recent tweets
print("Show 5 recent tweets: \n")
i = 1
for tweet in posts[0:5]:
  print(str(i) + ') ' + tweet.full_text + '\n')
  i = i + 1

#Creating dataframe
df = pd.DataFrame( [tweet.full_text for tweet in posts], columns=['Tweets'])

#Show first 5 rows
df.head()

# Creating a function to clean the tweets
def cleanTxt(text):
 text = re.sub('@[A-Za-z0–9]+', '', text) #Removing @mentions
 text = re.sub('#', '', text) # Removing '#' hash tag
 text = re.sub('RT[\s]+', '', text) # Removing Retweet
 text = re.sub('https?:\/\/\S+', '', text) # Removing hyperlink
 
 return text


# Cleaning the tweets
df['Tweets'] = df['Tweets'].apply(cleanTxt)

# Show the cleaned tweets
df

# Creating a function to get the subjectivity
def getSubjectivity(text):
   return TextBlob(text).sentiment.subjectivity

# Creating a function to get the polarity
def getPolarity(text):
   return  TextBlob(text).sentiment.polarity


# Creating two new columns 'Subjectivity' & 'Polarity'
df['Subjectivity'] = df['Tweets'].apply(getSubjectivity)
df['Polarity'] = df['Tweets'].apply(getPolarity)

# Show the new dataframe with columns 'Subjectivity' & 'Polarity'
df

# word cloud visualization
allWords = ' '.join([twts for twts in df['Tweets']])
wordCloud = WordCloud(width=500, height=300, random_state=21, max_font_size=110).generate(allWords)

plt.imshow(wordCloud, interpolation="bilinear")
plt.axis('off')
plt.show()

# Creating a function to compute negative (-1), neutral (0) and positive (+1) analysis
def getAnalysis(score):

  if score < 0:
    return 'Negative'
  elif score == 0:
    return 'Neutral'
  else:
    return 'Positive'

df['Analysis'] = df['Polarity'].apply(getAnalysis)
# Show the dataframe
df

# Printing positive tweets 
print('Printing positive tweets:\n')
j=1
sortedDF = df.sort_values(by=['Polarity']) #Sort the tweets
for i in range(0, sortedDF.shape[0] ):
  if( sortedDF['Analysis'][i] == 'Positive'):
    print(str(j) + ') '+ sortedDF['Tweets'][i])
    print()
    j= j+1

# Printing negative tweets  
print('Printing negative tweets:\n')
j=1
sortedDF = df.sort_values(by=['Polarity'],ascending=False) #Sort the tweets
for i in range(0, sortedDF.shape[0] ):
  if( sortedDF['Analysis'][i] == 'Negative'):
    print(str(j) + ') '+sortedDF['Tweets'][i])
    print()
    j=j+1

# Plotting 
plt.figure(figsize=(8,6)) 
for i in range(0, df.shape[0]):
  plt.scatter(df["Polarity"][i], df["Subjectivity"][i], color='Blue') 
# plt.scatter(x,y,color)   
plt.title('Sentiment Analysis') 
plt.xlabel('Polarity') 
plt.ylabel('Subjectivity') 
plt.show()

# Printing the percentage of positive tweets
ptweets = df[df.Analysis == 'Positive']
ptweets = ptweets['Tweets']
ptweets

round( (ptweets.shape[0] / df.shape[0]) * 100 , 1)

# Printing the percentage of negative tweets
ntweets = df[df.Analysis == 'Negative']
ntweets = ntweets['Tweets']
ntweets

round( (ntweets.shape[0] / df.shape[0]) * 100, 1)

# Show the value counts
df['Analysis'].value_counts()

# Plotting and visualizing the counts
plt.title('Sentiment Analysis')
plt.xlabel('Sentiment')
plt.ylabel('Counts')
df['Analysis'].value_counts().plot(kind = 'bar')
plt.show()